DROP TABLE 쿠폰이력 CASCADE CONSTRAINTS;
DROP TABLE 포인트 CASCADE CONSTRAINTS;
DROP TABLE 최근본상품 CASCADE CONSTRAINTS;
DROP TABLE 주문상세 CASCADE CONSTRAINTS;
DROP TABLE 장바구니 CASCADE CONSTRAINTS;
DROP TABLE 상품문의 CASCADE CONSTRAINTS;
DROP TABLE 리뷰 CASCADE CONSTRAINTS;
DROP TABLE 재고 CASCADE CONSTRAINTS;
DROP TABLE 배송 CASCADE CONSTRAINTS;
DROP TABLE 결제 CASCADE CONSTRAINTS;
DROP TABLE 이벤트 CASCADE CONSTRAINTS;
DROP TABLE 개인문의 CASCADE CONSTRAINTS;

DROP TABLE 주문 CASCADE CONSTRAINTS;
DROP TABLE 상품 CASCADE CONSTRAINTS;
DROP TABLE 쿠폰 CASCADE CONSTRAINTS;

DROP TABLE 회원 CASCADE CONSTRAINTS;
DROP TABLE 관리자 CASCADE CONSTRAINTS;
